name: dockerHDDM CI

on:
  push:
    branches: [ "master" ]

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm64 -f dockerfiles/0.9.8/Dockerfile.arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/hddm:0.9.8-arm64 . --push
    # - name: Docker image push
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hddm:0.9.8-amd64
